# git
alias ga='git add'
alias gap='git add -p'
alias gc='git commit'
alias gca='git commit --amend'
alias gch='git commit --amend -C HEAD'
alias gsta='git stash'
alias gstau='git stash -u'
alias gstaa='git stash --apply'
alias gcb='git_current_branch'
alias gp='git push'
alias gpp='git push origin `git_current_branch`'
alias gf='git fetch'
alias gm='git merge'
alias gmom='git merge origin/master'
alias gmum='git merge upstream/master'
alias gst='git status'
alias glog='git log'
alias grm='git rm'
alias grmr='git rm -r'
alias gtag='git tag'
alias gtaga='git tag -a'
alias gdt='git difftool'
alias gdtc='git difftool --cached'
alias gpot='git push origin --tags'
alias gput='git push upstream --tags'
alias gpoft='git push origin --follow-tags'
alias gpuft='git push upstream --follow-tags'
alias gcm='git checkout master'
alias gco='git checkout'

git-current-branch() {
    git branch | grep "^\* " | sed -e "s/^\* \(.*\)/\1/"
}

git-rm-remote-merged-branch() {
    # https://gist.github.com/miukoba/fc3c10a25c1c675c1e97
    # 引数としてmaster以外で除外するブランチを受け取る
    git remote prune origin
    # EXCLUDED_BRANCHS="-e master"
    # for B in "$@"; do
    #     EXCLUDED_BRANCHS="$EXCLUDED_BRANCHS -e $B"
    # done
    EXCLUDED_BRANCHS="^\*|master$"
    for B in "$@"; do
        EXCLUDED_BRANCHS="$EXCLUDED_BRANCHS|$B$"
    done
    git branch -r --merged master | sed -e "s/ *\(.*\) */\1/" | grep "^origin/" | sed -e "s/origin\///" | grep -v "HEAD -> " |  grep -vE $EXCLUDED_BRANCHS | xargs -I% git push --delete origin %
}

git-rm-local-merged-branch() {
    # https://gist.github.com/miukoba/fc3c10a25c1c675c1e97
    # 引数としてmaster以外で除外するブランチを受け取る
    EXCLUDED_BRANCHS="^\*|master$"
    for B in "$@"; do
        EXCLUDED_BRANCHS="$EXCLUDED_BRANCHS|$B$"
    done
    git branch --merged master | grep -vE $EXCLUDED_BRANCHS | xargs -I % git branch -d %
}

git-rm-merged-branch() {
  git-rm-local-merged-branch $@
  git-rm-remote-merged-branch $@
}
